apiVersion: batch/v1
kind: Job
metadata:
  name: bender
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: bender
          image: quay.io/buildah/stable:latest
          securityContext:
            privileged: true
          env:
            - name: CONTEXT
              value: "https://github.com/tlrmchlsmth/my_pods.git#refs/heads/main"
            - name: DOCKERFILE
              value: "bender/Dockerfile"
            - name: IMAGE
              value: "poker"
            - name: IMAGE_TAG
              value: "0.0.7"
            - name: BUILDAH_LAYERS
              value: "true"
            - name: REGISTRY_AUTH_FILE
              value: "/auth/config.json"
            - name: BUILDAH_ISOLATION
              value: "chroot"
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -euo pipefail
              buildah version
              buildah build \
                -f "${DOCKERFILE}" \
                -t "quay.io/tms/${IMAGE}:${IMAGE_TAG}" \
                "${CONTEXT}"
              buildah push "quay.io/tms/${IMAGE}:${IMAGE_TAG}"
          resources:
            requests:
              cpu: "16"
              memory: "32Gi"
              ephemeral-storage: "20Gi"
            limits:
              cpu: "16"
              memory: "32Gi"
              ephemeral-storage: "40Gi"
          volumeMounts:
            - name: auth
              mountPath: /auth
              readOnly: true
            - name: buildah-root
              mountPath: /buildah
      volumes:
        - name: auth
          secret:
            secretName: tms-bender-creds
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: buildah-root
          emptyDir: {}
