build VERSION:
  podman build --platform linux/amd64 -t quay.io/tms/pd-disagg-benchmark:{{VERSION}} .

push VERSION:
  podman push quay.io/tms/pd-disagg-benchmark:{{VERSION}}

start:
  kubectl apply -n llmd-test -f benchmark-interactive-pod.yaml
  
delete:
  kubectl delete -n llmd-test --now pod benchmark-interactive --cascade=background
  
exec:
  kubectl exec -n llmd-test -it benchmark-interactive -- /bin/bash
  
log:
  kubectl logs -n llmd-test benchmark-interactive
  
